apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
data:
  JWT_SECRET: "<base64-encoded-jwt-secret>"
  DB_PASSWORD: "<base64-encoded-db-password>"
  COGNITO_CLIENT_SECRET: "<base64-encoded-cognito-client-secret>"