apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: {{ .Values.image }}:latest
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: "<AWS_REGION>"
        - name: COGNITO_USER_POOL_ID
          value: "<COGNITO_USER_POOL_ID>"
        - name: COGNITO_APP_CLIENT_ID
          value: "<COGNITO_APP_CLIENT_ID>"
        - name: DB_HOST
          value: "<DB_HOST>"
        - name: DB_USER
          value: "<DB_USER>"
        - name: DB_PASSWORD
          value: "<DB_PASSWORD>"
        - name: DB_NAME
          value: "<DB_NAME>"
        - name: DB_MAX_OPEN_CONNS
          value: "<DB_MAX_OPEN_CONNS>"
        - name: DB_MAX_IDLE_CONNS
          value: "<DB_MAX_IDLE_CONNS>"
        - name: PORT
          value: "<PORT>"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10