name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: 381792517210.dkr.ecr.ap-southeast-2.amazonaws.com/simple-go-auth

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Run Go mod tidy
      run: go mod tidy

    - name: Run Go tests
      run: |
        go test ./... -v
        go test ./... -coverprofile=coverage.out
        go tool cover -func=coverage.out

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image
      run: |
        docker build -t $IMAGE_URI:latest ./simple-go-auth
        docker push $IMAGE_URI:latest

    - name: Deploy to Amazon ECS
      run: |
        aws ecs update-service \
          --cluster simple-go-auth-cluster \
          --service simple-go-auth-service \
          --region ap-southeast-2 \
          --force-new-deployment
