name: Secret Scan

on:
  schedule:
    - cron: "0 4 * * 0"  # every Sunday at 04:00 UTC
  workflow_dispatch: {}

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run TruffleHog filesystem scan
        # pull & run the official TruffleHog CLI as a container
        uses: docker://trufflesecurity/trufflehog:latest
        with:
          # tell the container what CLI args to pass
          args: filesystem --directory . --entropy True --branch HEAD
