name: Test CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U postgres -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Run Go mod tidy
        run: go mod tidy

      - name: Run Go tests
        env:
          DOTENV_FILE: .env.test
        run: |
          echo "PORT=1234" > .env.test
          echo "AWS_REGION=foo" >> .env.test
          echo "AWS_ACCESS_KEY_ID=test-key" >> .env.test
          echo "AWS_SECRET_ACCESS_KEY=test-secret" >> .env.test
          echo "DB_HOST=localhost" >> .env.test
          echo "DB_USER=postgres" >> .env.test
          echo "DB_PASSWORD=password" >> .env.test
          echo "DB_NAME=testdb" >> .env.test
          psql -h localhost -U postgres -d testdb -c "DELETE FROM users;"
          go test ./tests/auth_test.go ./tests/new_test.go ./tests/db_integration_test.go -v
