name: Vulnerability Scan

on:
  schedule:
    - cron: "0 3 * * 1"       # every Monday at 03:00 UTC
  workflow_dispatch: {}

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      - name: Scan container image
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL ${{ env.IMAGE_URI }}:latest
        env:
          IMAGE_URI: ${{ secrets.IMAGE_URI }}
